name: Windows check
on: [pull_request]
jobs:
  windows_chrome_rspec:
    name: Chrome
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install playwright-core via npm
        run: |
          npm install playwright-core@next
          ./node_modules/.bin/playwright-core install chromium
          ./node_modules/.bin/playwright-core install-deps chromium
      - run: bundle exec ruby development/generate_api.rb
      - name: Check example
        run: bundle exec rspec spec/integration/example_spec.rb
        env:
          PLAYWRIGHT_CLI_EXECUTABLE_PATH: ./node_modules/.bin/playwright-core
        timeout-minutes: 5
